name: "Protocol Buffer Stub Generation"
on:
  push:
    tags:
      - v**
jobs:
  generate:
    name: "Generate Protocol Buffer Stubs"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: ["billing", "catalog", "order", "search"]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - uses: bufbuild/buf-action@v1
        with:
          setup_only: true
      - name: Get Release Version
        run: echo "RELEASE_VERSION=$(echo ${{ github.ref }} | cut -d '/' -f 3)" >> $GITHUB_ENV
      - run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - name: Run make all
        run: make SERVICE_NAME=${{ matrix.service }} RELEASE_VERSION=${{ env.RELEASE_VERSION }} all
